version: '3.8'

services:
  frontend:
    build:
      context: ./job-recommender-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://jobrecommender-react.onrender.com

  backend:
    build:
      context: ./job-recommender-backend
    ports:
      - "5000:5000"
    volumes:
      - ./job-recommender-backend/data:/app/data
      - ./job-recommender-backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000 