services:
  - type: web
    name: job-recommender-frontend
    env: static
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://jobrecommender-react.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 