services:
  - type: web
    name: job-recommender-api
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install -r requirements.txt
      python3 -m spacy download en_core_web_sm
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 